// This file is automatically generated. Do not edit it directly.
// Supabase has been replaced with MongoDB authentication
// This is a dummy export to prevent import errors in old code

export const supabase = {
  auth: {
    signUp: () => Promise.reject(new Error('Use MongoDB auth instead')),
    signInWithPassword: () => Promise.reject(new Error('Use MongoDB auth instead')),
    signOut: () => Promise.reject(new Error('Use MongoDB auth instead')),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
  },
  from: () => ({
    select: () => Promise.resolve({ data: [], error: null }),
    insert: () => Promise.resolve({ data: null, error: null }),
    update: () => Promise.resolve({ data: null, error: null }),
    delete: () => Promise.resolve({ data: null, error: null }),
  }),
};